"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 4.2.5.
"""

# Standard libraries
from pathlib import Path
import os

# Build paths inside the project.
# ----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = str(BASE_DIR / 'apps')

# SECURITY WARNING: keep the secret key used in production secret!
# ----------------------------------------------------------------------------
SECRET_KEY = 'django-insecure-^s6qe1%gf4#-wsbh^i^5rpbqbg=ie^jc&uf*izzqg22-v*6d-w'

# SECURITY WARNING: don't run with debug turned on in production!
# ----------------------------------------------------------------------------
DEBUG = True

# Allowed hosts
# ----------------------------------------------------------------------------
ALLOWED_HOSTS = []

# Application definition
# ----------------------------------------------------------------------------
DJANGO_APPS = [
	'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = []
LOCAL_APPS = [
	'apps.core',  # o 'apps.core'
    'apps.usuario', #app destinada al usuario 
    'apps.ejercicio', #app destinada a ejercicio y comentarios
    'embed_video',
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Middleware
# ----------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration
# ----------------------------------------------------------------------------
ROOT_URLCONF = 'config.urls'

# Templates
# ----------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application
# ----------------------------------------------------------------------------
WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# ----------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'base_dir', # Nombre de tu base de datos
        'USER': 'root', # Nombre del usuario de la BD
        'PASSWORD': '', # Contraseña del usuario de la BD
        'HOST': 'localhost', # Dónde está alojada la BD (localmente en este caso)
        'PORT': '3306', # Puerto para MySQL, generalmente es 3306
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# ----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# ----------------------------------------------------------------------------
LANGUAGE_CODE = 'es-py'
TIME_ZONE = 'America/Asuncion'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# ----------------------------------------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [str(BASE_DIR / 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


#PARA MANEJAR ARCHIVOS MULTIMEDIA 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
# ----------------------------------------------------------------------------

AUTH_USER_MODEL = 'usuario.CustomUser'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
