# Generated by Django 4.2.5 on 2023-10-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejercicio', '0002_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(blank=True, default='Cuentanos que te parece la experiencia del usuario', max_length=200, null=True),
        ),
    ]
